alias day='date | cut --delimiter=" " --fields=1 | xargs echo Hello Abe this is'
alias time='date | cut --delimiter=" " --fields=5,6,7 | xargs echo it is'
alias caldr='cal -A1 -B1'
alias editbashrcfile='nano ~/.bashrc'
alias edittextfiles='nano'
alias browsetheweb='lynx google.com'
alias get='sudo apt-get install'
alias remove='sudo apt-get remove'
alias micro='/home/abe/micro'
alias c='clear'
alias getf='sudo apt-fast install'
alias rmf='sudo apt-fast install'
